[package]
name = "hello-world"
version = { workspace = true }
edition = "2024"
authors = []
license = "MIT"
description = ""
keywords = []
categories = []
repository = ""
documentation = ""

[dependencies]

[features]